export interface CountryAirport {
  country: string
  city: string
  airport: string
}

export const COUNTRY_AIRPORTS: CountryAirport[] = [
  { country: "Afghanistan", city: "Kabul", airport: "KBL" },
  { country: "Albania", city: "Tirana", airport: "TIA" },
  { country: "Algeria", city: "Algiers", airport: "ALG" },
  { country: "Andorra", city: "Andorra la Vella", airport: "LEU" },
  { country: "Angola", city: "Luanda", airport: "LAD" },
  { country: "Antigua and Barbuda", city: "St. John's", airport: "ANU" },
  { country: "Argentina", city: "Buenos Aires", airport: "EZE" },
  { country: "Armenia", city: "Yerevan", airport: "EVN" },
  { country: "Australia", city: "Sydney", airport: "SYD" },
  { country: "Austria", city: "Vienna", airport: "VIE" },
  { country: "Azerbaijan", city: "Baku", airport: "GYD" },
  { country: "Bahamas", city: "Nassau", airport: "NAS" },
  { country: "Bahrain", city: "Manama", airport: "BAH" },
  { country: "Bangladesh", city: "Dhaka", airport: "DAC" },
  { country: "Barbados", city: "Bridgetown", airport: "BGI" },
  { country: "Belarus", city: "Minsk", airport: "MSQ" },
  { country: "Belgium", city: "Brussels", airport: "BRU" },
  { country: "Belize", city: "Belize City", airport: "BZE" },
  { country: "Benin", city: "Cotonou", airport: "COO" },
  { country: "Bhutan", city: "Paro", airport: "PBH" },
  { country: "Bolivia", city: "La Paz", airport: "LPB" },
  { country: "Bosnia and Herzegovina", city: "Sarajevo", airport: "SJJ" },
  { country: "Botswana", city: "Gaborone", airport: "GBE" },
  { country: "Brazil", city: "São Paulo", airport: "GRU" },
  { country: "Brunei", city: "Bandar Seri Begawan", airport: "BWN" },
  { country: "Bulgaria", city: "Sofia", airport: "SOF" },
  { country: "Burkina Faso", city: "Ouagadougou", airport: "OUA" },
  { country: "Burundi", city: "Bujumbura", airport: "BJM" },
  { country: "Cabo Verde", city: "Praia", airport: "RAI" },
  { country: "Cambodia", city: "Phnom Penh", airport: "PNH" },
  { country: "Cameroon", city: "Douala", airport: "DLA" },
  { country: "Canada", city: "Toronto", airport: "YYZ" },
  { country: "Central African Republic", city: "Bangui", airport: "BGF" },
  { country: "Chad", city: "N'Djamena", airport: "NDJ" },
  { country: "Chile", city: "Santiago", airport: "SCL" },
  { country: "China", city: "Beijing", airport: "PEK" },
  { country: "Colombia", city: "Bogotá", airport: "BOG" },
  { country: "Comoros", city: "Moroni", airport: "HAH" },
  { country: "Congo (DRC)", city: "Kinshasa", airport: "FIH" },
  { country: "Congo (Republic)", city: "Brazzaville", airport: "BZV" },
  { country: "Costa Rica", city: "San José", airport: "SJO" },
  { country: "Croatia", city: "Zagreb", airport: "ZAG" },
  { country: "Cuba", city: "Havana", airport: "HAV" },
  { country: "Cyprus", city: "Larnaca", airport: "LCA" },
  { country: "Czechia", city: "Prague", airport: "PRG" },
  { country: "Denmark", city: "Copenhagen", airport: "CPH" },
  { country: "Djibouti", city: "Djibouti", airport: "JIB" },
  { country: "Dominica", city: "Roseau", airport: "DOM" },
  { country: "Dominican Republic", city: "Santo Domingo", airport: "SDQ" },
  { country: "Ecuador", city: "Quito", airport: "UIO" },
  { country: "Egypt", city: "Cairo", airport: "CAI" },
  { country: "El Salvador", city: "San Salvador", airport: "SAL" },
  { country: "Equatorial Guinea", city: "Malabo", airport: "SSG" },
  { country: "Eritrea", city: "Asmara", airport: "ASM" },
  { country: "Estonia", city: "Tallinn", airport: "TLL" },
  { country: "Eswatini", city: "Manzini", airport: "SHO" },
  { country: "Ethiopia", city: "Addis Ababa", airport: "ADD" },
  { country: "Fiji", city: "Nadi", airport: "NAN" },
  { country: "Finland", city: "Helsinki", airport: "HEL" },
  { country: "France", city: "Paris", airport: "CDG" },
  { country: "Gabon", city: "Libreville", airport: "LBV" },
  { country: "Gambia", city: "Banjul", airport: "BJL" },
  { country: "Georgia", city: "Tbilisi", airport: "TBS" },
  { country: "Germany", city: "Frankfurt", airport: "FRA" },
  { country: "Ghana", city: "Accra", airport: "ACC" },
  { country: "Greece", city: "Athens", airport: "ATH" },
  { country: "Grenada", city: "St. George's", airport: "GND" },
  { country: "Guatemala", city: "Guatemala City", airport: "GUA" },
  { country: "Guinea", city: "Conakry", airport: "CKY" },
  { country: "Guinea-Bissau", city: "Bissau", airport: "OXB" },
  { country: "Guyana", city: "Georgetown", airport: "GEO" },
  { country: "Haiti", city: "Port-au-Prince", airport: "PAP" },
  { country: "Honduras", city: "Tegucigalpa", airport: "TGU" },
  { country: "Hungary", city: "Budapest", airport: "BUD" },
  { country: "Iceland", city: "Reykjavik", airport: "KEF" },
  { country: "India", city: "New Delhi", airport: "DEL" },
  { country: "Indonesia", city: "Jakarta", airport: "CGK" },
  { country: "Iran", city: "Tehran", airport: "IKA" },
  { country: "Iraq", city: "Baghdad", airport: "BGW" },
  { country: "Ireland", city: "Dublin", airport: "DUB" },
  { country: "Israel", city: "Tel Aviv", airport: "TLV" },
  { country: "Italy", city: "Rome", airport: "FCO" },
  { country: "Jamaica", city: "Kingston", airport: "KIN" },
  { country: "Japan", city: "Tokyo", airport: "NRT" },
  { country: "Jordan", city: "Amman", airport: "AMM" },
  { country: "Kazakhstan", city: "Almaty", airport: "ALA" },
  { country: "Kenya", city: "Nairobi", airport: "NBO" },
  { country: "Kiribati", city: "Tarawa", airport: "TRW" },
  { country: "Kuwait", city: "Kuwait City", airport: "KWI" },
  { country: "Kyrgyzstan", city: "Bishkek", airport: "FRU" },
  { country: "Laos", city: "Vientiane", airport: "VTE" },
  { country: "Latvia", city: "Riga", airport: "RIX" },
  { country: "Lebanon", city: "Beirut", airport: "BEY" },
  { country: "Lesotho", city: "Maseru", airport: "MSU" },
  { country: "Liberia", city: "Monrovia", airport: "ROB" },
  { country: "Libya", city: "Tripoli", airport: "TIP" },
  { country: "Liechtenstein", city: "Zurich", airport: "ZRH" },
  { country: "Lithuania", city: "Vilnius", airport: "VNO" },
  { country: "Luxembourg", city: "Luxembourg", airport: "LUX" },
  { country: "Madagascar", city: "Antananarivo", airport: "TNR" },
  { country: "Malawi", city: "Lilongwe", airport: "LLW" },
  { country: "Malaysia", city: "Kuala Lumpur", airport: "KUL" },
  { country: "Maldives", city: "Malé", airport: "MLE" },
  { country: "Mali", city: "Bamako", airport: "BKO" },
  { country: "Malta", city: "Valletta", airport: "MLA" },
  { country: "Marshall Islands", city: "Majuro", airport: "MAJ" },
  { country: "Mauritania", city: "Nouakchott", airport: "NKC" },
  { country: "Mauritius", city: "Port Louis", airport: "MRU" },
  { country: "Mexico", city: "Mexico City", airport: "MEX" },
  { country: "Micronesia", city: "Pohnpei", airport: "PNI" },
  { country: "Moldova", city: "Chișinău", airport: "KIV" },
  { country: "Monaco", city: "Nice", airport: "NCE" },
  { country: "Mongolia", city: "Ulaanbaatar", airport: "ULN" },
  { country: "Montenegro", city: "Podgorica", airport: "TGD" },
  { country: "Morocco", city: "Casablanca", airport: "CMN" },
  { country: "Mozambique", city: "Maputo", airport: "MPM" },
  { country: "Myanmar", city: "Yangon", airport: "RGN" },
  { country: "Namibia", city: "Windhoek", airport: "WDH" },
  { country: "Nauru", city: "Yaren", airport: "INU" },
  { country: "Nepal", city: "Kathmandu", airport: "KTM" },
  { country: "Netherlands", city: "Amsterdam", airport: "AMS" },
  { country: "New Zealand", city: "Auckland", airport: "AKL" },
  { country: "Nicaragua", city: "Managua", airport: "MGA" },
  { country: "Niger", city: "Niamey", airport: "NIM" },
  { country: "Nigeria", city: "Lagos", airport: "LOS" },
  { country: "North Korea", city: "Pyongyang", airport: "FNJ" },
  { country: "North Macedonia", city: "Skopje", airport: "SKP" },
  { country: "Norway", city: "Oslo", airport: "OSL" },
  { country: "Oman", city: "Muscat", airport: "MCT" },
  { country: "Pakistan", city: "Karachi", airport: "KHI" },
  { country: "Palau", city: "Koror", airport: "ROR" },
  { country: "Palestine", city: "Ramallah", airport: "JRS" },
  { country: "Panama", city: "Panama City", airport: "PTY" },
  { country: "Papua New Guinea", city: "Port Moresby", airport: "POM" },
  { country: "Paraguay", city: "Asunción", airport: "ASU" },
  { country: "Peru", city: "Lima", airport: "LIM" },
  { country: "Philippines", city: "Manila", airport: "MNL" },
  { country: "Poland", city: "Warsaw", airport: "WAW" },
  { country: "Portugal", city: "Lisbon", airport: "LIS" },
  { country: "Qatar", city: "Doha", airport: "DOH" },
  { country: "Romania", city: "Bucharest", airport: "OTP" },
  { country: "Russia", city: "Moscow", airport: "SVO" },
  { country: "Rwanda", city: "Kigali", airport: "KGL" },
  { country: "Saint Kitts and Nevis", city: "Basseterre", airport: "SKB" },
  { country: "Saint Lucia", city: "Castries", airport: "UVF" },
  { country: "Saint Vincent and the Grenadines", city: "Kingstown", airport: "SVD" },
  { country: "Samoa", city: "Apia", airport: "APW" },
  { country: "San Marino", city: "Rimini", airport: "RMI" },
  { country: "Sao Tome and Principe", city: "São Tomé", airport: "TMS" },
  { country: "Saudi Arabia", city: "Riyadh", airport: "RUH" },
  { country: "Senegal", city: "Dakar", airport: "DSS" },
  { country: "Serbia", city: "Belgrade", airport: "BEG" },
  { country: "Seychelles", city: "Mahé", airport: "SEZ" },
  { country: "Sierra Leone", city: "Freetown", airport: "FNA" },
  { country: "Singapore", city: "Singapore", airport: "SIN" },
  { country: "Slovakia", city: "Bratislava", airport: "BTS" },
  { country: "Slovenia", city: "Ljubljana", airport: "LJU" },
  { country: "Solomon Islands", city: "Honiara", airport: "HIR" },
  { country: "Somalia", city: "Mogadishu", airport: "MGQ" },
  { country: "South Africa", city: "Johannesburg", airport: "JNB" },
  { country: "South Korea", city: "Seoul", airport: "ICN" },
  { country: "South Sudan", city: "Juba", airport: "JUB" },
  { country: "Spain", city: "Madrid", airport: "MAD" },
  { country: "Sri Lanka", city: "Colombo", airport: "CMB" },
  { country: "Sudan", city: "Khartoum", airport: "KRT" },
  { country: "Suriname", city: "Paramaribo", airport: "PBM" },
  { country: "Sweden", city: "Stockholm", airport: "ARN" },
  { country: "Switzerland", city: "Zurich", airport: "ZRH" },
  { country: "Syria", city: "Damascus", airport: "DAM" },
  { country: "Taiwan", city: "Taipei", airport: "TPE" },
  { country: "Tajikistan", city: "Dushanbe", airport: "DYU" },
  { country: "Tanzania", city: "Dar es Salaam", airport: "DAR" },
  { country: "Thailand", city: "Bangkok", airport: "BKK" },
  { country: "Timor-Leste", city: "Dili", airport: "DIL" },
  { country: "Togo", city: "Lomé", airport: "LFW" },
  { country: "Tonga", city: "Nuku'alofa", airport: "TBU" },
  { country: "Trinidad and Tobago", city: "Port of Spain", airport: "POS" },
  { country: "Tunisia", city: "Tunis", airport: "TUN" },
  { country: "Turkey", city: "Istanbul", airport: "IST" },
  { country: "Turkmenistan", city: "Ashgabat", airport: "ASB" },
  { country: "Tuvalu", city: "Funafuti", airport: "FUN" },
  { country: "Uganda", city: "Entebbe", airport: "EBB" },
  { country: "Ukraine", city: "Kyiv", airport: "KBP" },
  { country: "United Arab Emirates", city: "Dubai", airport: "DXB" },
  { country: "United Kingdom", city: "London", airport: "LHR" },
  { country: "United States", city: "New York", airport: "JFK" },
  { country: "Uruguay", city: "Montevideo", airport: "MVD" },
  { country: "Uzbekistan", city: "Tashkent", airport: "TAS" },
  { country: "Vanuatu", city: "Port Vila", airport: "VLI" },
  { country: "Vatican City", city: "Rome", airport: "FCO" },
  { country: "Venezuela", city: "Caracas", airport: "CCS" },
  { country: "Vietnam", city: "Ho Chi Minh City", airport: "SGN" },
  { country: "Yemen", city: "Sana'a", airport: "SAH" },
  { country: "Zambia", city: "Lusaka", airport: "LUN" },
  { country: "Zimbabwe", city: "Harare", airport: "HRE" },
]

export function findCountryByAirport(code: string) {
  return COUNTRY_AIRPORTS.find(
    (item) => item.airport.toUpperCase() === code.toUpperCase()
  )
}

export function filterCountries(query: string) {
  const q = query.trim().toLowerCase()
  if (!q) return COUNTRY_AIRPORTS

  return COUNTRY_AIRPORTS.filter(
    (item) =>
      item.country.toLowerCase().includes(q) ||
      item.city.toLowerCase().includes(q) ||
      item.airport.toLowerCase().includes(q)
  )
}
