export type ExploreDestination = {
  id: string
  name: string
  country: string
  image: string
  rating: number
  reviews: number
  priceFrom: number
  region: string
  season: string
  description: string
  featured?: boolean
  trending?: boolean
}

export const exploreDestinations: ExploreDestination[] = [
  {
    id: "e1",
    name: "Santorini",
    country: "Greece",
    image: "https://images.unsplash.com/photo-1613395877344-13d4a8dbf0bd?w=800&q=80",
    rating: 4.9,
    reviews: 2840,
    priceFrom: 890,
    region: "Europe",
    season: "Summer",
    description: "Whitewashed villages, caldera views, and Mediterranean sunsets.",
    featured: true,
    trending: true,
  },
  {
    id: "e2",
    name: "Kyoto",
    country: "Japan",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    rating: 4.8,
    reviews: 3120,
    priceFrom: 1120,
    region: "Asia",
    season: "Spring",
    description: "Temples, cherry blossoms, and timeless Japanese culture.",
    featured: true,
  },
  {
    id: "e3",
    name: "Cape Town",
    country: "South Africa",
    image: "https://images.unsplash.com/photo-1580060839134-75a5e2a67363?w=800&q=80",
    rating: 4.7,
    reviews: 1560,
    priceFrom: 760,
    region: "Africa",
    season: "Autumn",
    description: "Table Mountain, coastal drives, and vibrant food scene.",
    trending: true,
  },
  {
    id: "e4",
    name: "New York",
    country: "USA",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
    rating: 4.6,
    reviews: 4200,
    priceFrom: 980,
    region: "Americas",
    season: "Winter",
    description: "Iconic skyline, Broadway, and world-class museums.",
    featured: true,
    trending: true,
  },
  {
    id: "e5",
    name: "Queenstown",
    country: "New Zealand",
    image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80",
    rating: 4.9,
    reviews: 980,
    priceFrom: 1340,
    region: "Oceania",
    season: "Summer",
    description: "Adventure capital with lakes, peaks, and outdoor thrills.",
  },
  {
    id: "e6",
    name: "Marrakech",
    country: "Morocco",
    image: "https://images.unsplash.com/photo-1517821362941-f7f753107065?w=800&q=80",
    rating: 4.5,
    reviews: 1890,
    priceFrom: 540,
    region: "Africa",
    season: "Spring",
    description: "Souks, riads, and the gateway to the Sahara.",
    trending: true,
  },
  {
    id: "e7",
    name: "Paris",
    country: "France",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
    rating: 4.8,
    reviews: 5100,
    priceFrom: 1180,
    region: "Europe",
    season: "Spring",
    description: "Cafés, art museums, and romantic boulevards.",
    featured: true,
    trending: true,
  },
  {
    id: "e8",
    name: "Rome",
    country: "Italy",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80",
    rating: 4.7,
    reviews: 3900,
    priceFrom: 820,
    region: "Europe",
    season: "Autumn",
    description: "Ancient ruins, pasta, and piazza life.",
    trending: true,
  },
  {
    id: "e9",
    name: "Bali",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1537996194471-f6576caed54d?w=800&q=80",
    rating: 4.8,
    reviews: 2700,
    priceFrom: 620,
    region: "Asia",
    season: "Summer",
    description: "Rice terraces, temples, and beach retreats.",
    featured: true,
    trending: true,
  },
  {
    id: "e10",
    name: "Bangkok",
    country: "Thailand",
    image: "https://images.unsplash.com/photo-1563492065-73a5a1e3d0c4?w=800&q=80",
    rating: 4.6,
    reviews: 3300,
    priceFrom: 480,
    region: "Asia",
    season: "Winter",
    description: "Street food, golden temples, and river markets.",
    trending: true,
  },
  {
    id: "e11",
    name: "Seoul",
    country: "South Korea",
    image: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&q=80",
    rating: 4.7,
    reviews: 2100,
    priceFrom: 940,
    region: "Asia",
    season: "Autumn",
    description: "K-culture, palaces, and neon city nights.",
    featured: true,
  },
  {
    id: "e12",
    name: "Cairo",
    country: "Egypt",
    image: "https://images.unsplash.com/photo-1572252009281-8fdb8fa3b768?w=800&q=80",
    rating: 4.5,
    reviews: 1750,
    priceFrom: 590,
    region: "Africa",
    season: "Winter",
    description: "Pyramids, Nile cruises, and ancient wonders.",
    featured: true,
  },
  {
    id: "e13",
    name: "Nairobi",
    country: "Kenya",
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800&q=80",
    rating: 4.6,
    reviews: 1320,
    priceFrom: 1050,
    region: "Africa",
    season: "Summer",
    description: "Safari gateways and vibrant urban culture.",
    trending: true,
  },
  {
    id: "e14",
    name: "Rio de Janeiro",
    country: "Brazil",
    image: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=800&q=80",
    rating: 4.7,
    reviews: 3600,
    priceFrom: 710,
    region: "Americas",
    season: "Summer",
    description: "Copacabana beaches, samba, and mountain views.",
    featured: true,
    trending: true,
  },
  {
    id: "e15",
    name: "Cancún",
    country: "Mexico",
    image: "https://images.unsplash.com/photo-1510097467904-438e2d35f3d0?w=800&q=80",
    rating: 4.5,
    reviews: 2900,
    priceFrom: 650,
    region: "Americas",
    season: "Spring",
    description: "Caribbean coast, ruins, and resort escapes.",
    trending: true,
  },
  {
    id: "e16",
    name: "Vancouver",
    country: "Canada",
    image: "https://images.unsplash.com/photo-1559511260-66a27e798e83?w=800&q=80",
    rating: 4.6,
    reviews: 1880,
    priceFrom: 1020,
    region: "Americas",
    season: "Autumn",
    description: "Mountains meet the Pacific in a walkable city.",
    featured: true,
  },
  {
    id: "e17",
    name: "Sydney",
    country: "Australia",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8ece8?w=800&q=80",
    rating: 4.8,
    reviews: 4100,
    priceFrom: 1280,
    region: "Oceania",
    season: "Spring",
    description: "Harbour icons, beaches, and coastal trails.",
    featured: true,
    trending: true,
  },
  {
    id: "e18",
    name: "Fiji",
    country: "Fiji",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    rating: 4.7,
    reviews: 980,
    priceFrom: 890,
    region: "Oceania",
    season: "Winter",
    description: "Turquoise lagoons and island hospitality.",
    trending: true,
  },
]

export const exploreRegions = ["All", "Europe", "Asia", "Africa", "Americas", "Oceania"]
export const exploreSeasons = ["All", "Spring", "Summer", "Autumn", "Winter"]
export const explorePriceRanges = ["Any", "Under $700", "$700–$1000", "$1000+"]
